# Generated by Django 2.0 on 2018-04-06 08:42

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20180406_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to=main_app.models.get_image_path),
        ),
    ]
